config:
  debug: false

  host: "0.0.0.0"
  port: 9999
  secret-key: "key"

  methods:
    NuVotifier:
      enabled: false
    Commands:
      enabled: false
      commands: [
        "give $player diamond 20"
      ]
    MySqlRequests:
      enabled: false
      url: "jdbc:mysql://localhost:3306/"

      database: "mineserv"
      username: "mineserv"
      password: "mineserv"

      sqlQuery: [
        "UPDATE `iconomy` SET `balance`=`balance`+100 WHERE `username`='$player'"
      ]